#-------Sdet--------------------------------------------#

all: codea.vbe \
     codej.vbe \
     codem.vbe \
     codeo.vbe \
     coder.vbe \
     code_boom \
     code_loon
	     @echo "<-- Generated"

#-------Finite State Machine Synthesis-----------------#

vhd_to_fsm:
	rename .vhd .fsm *.vhd

codea.vbe: code.fsm
	@echo "    Encoding Synthesis -> codea.vbe"
	syf -CEV -a code
 
codej.vbe: code.fsm
	@echo "    Encoding Synthesis  -> codej.vbe"
	syf -CEV -j code
 
codem.vbe: code.fsm
	@echo "    Encoding Synthesis  -> codem.vbe"
	syf -CEV -m code
 
codeo.vbe: code.fsm
	@echo "    Encoding Synthesis  -> codeo.vbe"
	syf -CEV -o code
 
coder.vbe: code.fsm
	@echo "    Encoding Synthesis  -> coder.vbe"
	syf -CEV -r code

code_boom: codea_b.vbe codej_b.vbe codem_b.vbe \
	   codeo_b.vbe coder_b.vbe

%_b.vbe: %.vbe
	 @echo "   Boolean Optimiztaion -> $@  "
	 boom -V -d 50 $* $*_b > $*_boom.out

code_boog: codea_b.vst codej_b.vst codem_b.vst \
	   codeo_b.vst coder_b.vst

code_loon: codea_b_l.vst codej_b_l.vst codem_b_l.vst \
	   codeo_b_l.vst coder_b_l.vst

%.vst : %.vbe paramfile.lax
	@echo "  Logical Synsthesis -> $@ "
	boog -x 1 -l paramfile $* > $*_boog.out

%_l.vst : %.vst paramfile.lax
	@echo "  Netlist OPtimization -> $@ "
	loon -x 1 -l paramfile $* $*_l > $*_loon.out

%_b_l_net.vbe : %_b_l.vst %.vbe
	@echo " Formal checking -> $@ "
	flatbeh $*_b_l $*_b_l_net > $*_flatbeh.out
	proof -d $* $*_b_l_net > $*_proof.out

ac_scapin_registers:
	cat codej_b_l.vst | grep sff

%_scan.vst : %.vst scan.path
	@echo " scan-path insertion -> $@ "
	scapin -VRB $* scan $*_scan > scapin.out

#-------Clean Up---------------------------------------#

clean :
	rm -f  *.vbe *.enc *~
	@echo "Erase all the files generated by the makefile"

